Remove tgid map
sustainable-computing-io/kepler pull request #1554
Opened 2024-06-18 15:45 UTC by marceloamaral

With the new task structure in the tracepoint in the code, we can now directly get the previous running task tgid, so that we can remove the map to track and translate the pid to tgid.

2024-06-18 16:11 UTC, dave-tucker requested changes

2024-06-18 16:11 UTC, dave-tucker commented on bpfassets/libbpf/src/kepler.bpf.c
> +
You don't need to create an new struct - this wouldn't work anyway as tgid isn't the first field (that's state)

2024-06-18 16:11 UTC, dave-tucker commented on bpfassets/libbpf/src/kepler.bpf.c
>  } __attribute__((preserve_access_index));
Add `unsigned int tgid;` into `struct task_struct`.
It will get CO:RE relocated to the right offset in task_struct at load time.

2024-06-18 16:11 UTC, dave-tucker commented on bpfassets/libbpf/src/kepler.bpf.c
> +static unsigned int get_task_tgid(void *task)
No need for a function here. With the change above you can just use `prev_task->tgid` directly.

2024-06-19 07:20 UTC, dave-tucker commented on bpfassets/libbpf/src/kepler.bpf.c
> +	prev_tgid = next_task->tgid;
Should this be prev_task->tgid?

2024-07-01 08:36 UTC, marceloamaral commented on bpfassets/libbpf/src/kepler.bpf.c
> +	prev_tgid = next_task->tgid;
Yeap, fixed!

2024-07-01 12:17 UTC, rootfs approved these changes

2024-07-02 15:18 UTC, dave-tucker approved these changes

2024-07-02 15:18 UTC, merged