[Snyk] Security upgrade alpine from 3.7 to 3.17
sustainable-computing-io/kepler pull request #1564
Opened 2024-06-23 06:22 UTC by rootfs

<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br />![snyk-top-banner](https://github.com/andygongea/OWASP-Benchmark/assets/818805/c518c423-16fe-447e-b67f-ad5a49b5d123)

### Snyk has created this PR to fix 1 vulnerabilities in the dockerfile dependencies of this project.

Keeping your Docker base image up-to-date means you’ll benefit from security fixes in the latest version of your chosen image.

#### Snyk changed the following file(s):

- `vendor/github.com/jaypipes/ghw/Dockerfile`

We recommend upgrading to `alpine:3.17`, as this image has only **0** known vulnerabilities. To do this, merge this pull request, then verify your application still works as expected.

#### Vulnerabilities that will be fixed with an upgrade:

|  | Issue | Score | 
:-------------------------:|:-------------------------|:-------------------------
![critical severity](https://res.cloudinary.com/snyk/image/upload/w_20,h_20/v1561977819/icon/c.png 'critical severity') | Out-of-bounds Write <br/>[SNYK-ALPINE37-MUSL-458286](https://snyk.io/vuln/SNYK-ALPINE37-MUSL-458286) | &nbsp;&nbsp;**714**&nbsp;&nbsp; 
![critical severity](https://res.cloudinary.com/snyk/image/upload/w_20,h_20/v1561977819/icon/c.png 'critical severity') | Out-of-bounds Write <br/>[SNYK-ALPINE37-MUSL-458286](https://snyk.io/vuln/SNYK-ALPINE37-MUSL-458286) | &nbsp;&nbsp;**714**&nbsp;&nbsp; 

---

> [!IMPORTANT]
>
> - Check the changes in this PR to ensure they won't cause issues with your project.
> - Max score is 1000. Note that the real score may have changed since the PR was raised.
> - This PR was automatically created by Snyk using the credentials of a real user.

---

**Note:** _You are seeing this because you or someone else with access to this repository has authorized Snyk to open fix PRs._

For more information: <img src="https://api.segment.io/v1/pixel/track?data=eyJ3cml0ZUtleSI6InJyWmxZcEdHY2RyTHZsb0lYd0dUcVg4WkFRTnNCOUEwIiwiYW5vbnltb3VzSWQiOiI1Yzk5NjYxMy04NTAzLTQ4YjctYTZjMC1jM2YyNWNhODk5NGUiLCJldmVudCI6IlBSIHZpZXdlZCIsInByb3BlcnRpZXMiOnsicHJJZCI6IjVjOTk2NjEzLTg1MDMtNDhiNy1hNmMwLWMzZjI1Y2E4OTk0ZSJ9fQ==" width="0" height="0"/>
🧐 [View latest project report](https://app.snyk.io/org/kepler-SPYntdGxx3BzncPKDJmbmB/project/517d6c3f-6bbd-44ba-ace2-a5240453ea2b?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;fix-pr)
📜 [Customise PR templates](https://docs.snyk.io/scan-using-snyk/pull-requests/snyk-fix-pull-or-merge-requests/customize-pr-templates)
🛠 [Adjust project settings](https://app.snyk.io/org/kepler-SPYntdGxx3BzncPKDJmbmB/project/517d6c3f-6bbd-44ba-ace2-a5240453ea2b?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;fix-pr/settings)
📚 [Read about Snyk's upgrade logic](https://support.snyk.io/hc/en-us/articles/360003891078-Snyk-patches-to-fix-vulnerabilities)

---

**Learn how to fix vulnerabilities with free interactive lessons:**

🦉 [Learn about vulnerability in an interactive lesson of Snyk Learn.](https://learn.snyk.io/?loc&#x3D;fix-pr)

[//]: # 'snyk:metadata:{"customTemplate":{"variablesUsed":[],"fieldsUsed":[]},"dependencies":[{"name":"alpine","from":"3.7","to":"3.17"}],"env":"prod","issuesToFix":[{"exploit_maturity":"No Known Exploit","id":"SNYK-ALPINE37-MUSL-458286","priority_score":714,"priority_score_factors":[{"type":"fixability","label":true,"score":214},{"type":"severity","label":"critical","score":500},{"type":"scoreVersion","label":"v1","score":1}],"severity":"critical","title":"Out-of-bounds Write"},{"exploit_maturity":"No Known Exploit","id":"SNYK-ALPINE37-MUSL-458286","priority_score":714,"priority_score_factors":[{"type":"fixability","label":true,"score":214},{"type":"severity","label":"critical","score":500},{"type":"scoreVersion","label":"v1","score":1}],"severity":"critical","title":"Out-of-bounds Write"}],"prId":"5c996613-8503-48b7-a6c0-c3f25ca8994e","prPublicId":"5c996613-8503-48b7-a6c0-c3f25ca8994e","packageManager":"dockerfile","priorityScoreList":[714],"projectPublicId":"517d6c3f-6bbd-44ba-ace2-a5240453ea2b","projectUrl":"https://app.snyk.io/org/kepler-SPYntdGxx3BzncPKDJmbmB/project/517d6c3f-6bbd-44ba-ace2-a5240453ea2b?utm_source=github&utm_medium=referral&page=fix-pr","prType":"fix","templateFieldSources":{"branchName":"default","commitMessage":"default","description":"default","title":"default"},"templateVariants":["updated-fix-title","priorityScore"],"type":"auto","upgrade":["SNYK-ALPINE37-MUSL-458286","SNYK-ALPINE37-MUSL-458286"],"vulns":["SNYK-ALPINE37-MUSL-458286"],"patch":[],"isBreakingChange":false,"remediationStrategy":"vuln"}'

2024-06-23 06:29 UTC, SamYuan1990 commented
why should we update a docker file to fix CVE in vendor folder?
we should make Snyk excludes docker file in vendor folder.

2024-06-23 06:29 UTC, SamYuan1990 requested changes
I suppose we should not merge this PR.

2024-06-23 11:55 UTC, dave-tucker commented
Correct! This should be closed

2024-09-06 15:44 UTC, dave-tucker commented
Closing again. Snyk (or any other tools) should not touch files in the `vendor` directory.

2024-09-06 15:44 UTC, closed without merging