add missing info to Makefile help
sustainable-computing-io/kepler pull request #1639
Opened 2024-07-25 17:36 UTC by arthurus-rex

Fill in missing Makefile help entries with brief descriptions, so all available make options are obvious.  Also created 'testing' section so users can run single testing tools if desired.

2024-07-26 13:39 UTC, maryamtahhan requested changes
Overall Looks good. There's a couple of comments in the wrong places.

2024-07-26 13:39 UTC, maryamtahhan commented on Makefile
> +clean: clean-cross-build ## Undeploy Kepler.
```suggestion
clean: clean-cross-build ## Clean Kepler build
```

2024-07-26 13:39 UTC, maryamtahhan commented on Makefile
> +image_builder_check:
```suggestion
image_builder_check:
```

2024-07-26 13:39 UTC, maryamtahhan commented on Makefile
> +clean_build_local: ## Undeploy Kepler for multiple archs.
```suggestion
clean_build_local: ## Clean local build directory
```

2024-07-26 13:39 UTC, maryamtahhan commented on Makefile
> +copy_build_local: ## Copy bin to $(OUTPUT_DIR)/bin.
```suggestion
copy_build_local: ## Copy Kepler binary to $(OUTPUT_DIR)/bin.
```

2024-07-26 13:39 UTC, maryamtahhan commented on Makefile
> +escapes_detect: tidy-vendor ## Tidy Go dependencies.
```suggestion
escapes_detect: tidy-vendor 
```

I would move the description you added to the tidy-vendor target

2024-07-26 13:39 UTC, maryamtahhan commented on Makefile
> +dev-restart: dev-clean dev ## Clean development environment.
```suggestion
dev-restart: dev-clean dev ## Restart development environment.
```

2024-07-26 15:27 UTC, maryamtahhan approved these changes

2024-07-27 00:32 UTC, sthaha approved these changes

2024-07-27 00:32 UTC, merged