feat(validator): incorporate MAE in validations
sustainable-computing-io/kepler pull request #1815
Opened 2024-10-17 18:29 UTC by vprashar2929

This commit adds MAE to the computation. The validator runs will now include MAE results in the output.

The MSE, MAE and MAPE are now computed using the scikit-learn library

2024-10-18 05:35 UTC, sthaha commented on e2e/tools/validator/src/validator/prometheus/__init__.py
> +        return ValueOrError(value=np.abs(np.subtract(actual, predicted)).mean())
IIUC,  https://www.statisticshowto.com/absolute-error/ 
the `abs` should be applied to `subtract`  and not to the mean 
```
|(1  + - 1 ) / 2 | != ( |1|  + |-1| ) / 2 
```
Hence 
```
def mean_absolute_error(actual, predicted):
    return np.mean(np.abs(actual - predicted))
```

2024-10-18 05:39 UTC, sthaha requested changes
Can you please check the mae calculation ? 
Alternatively, how about we use the functions in scikit.metrics ? 

See usage: https://github.com/sustainable-computing-io/kepler-experimental/blob/main/st/power-model/src/power_model/trainer/runner.py#L14

2024-10-22 14:33 UTC, rootfs approved these changes

2024-10-22 23:04 UTC, sthaha approved these changes

2024-10-22 23:04 UTC, merged