allow expose metrics with options
sustainable-computing-io/kepler pull request #290
Opened 2022-10-11 03:16 UTC by jichenjc

Signed-off-by: jichenjc <jichenjc@cn.ibm.com>

2022-10-11 09:30 UTC, marceloamaral commented on cmd/exporter.go
> +	enableHardwareCounterMetrics = flag.Bool("enable-hardware-counter-metrics", true, "whether expose hardware counter metrics")
`enableHardwareCounterMetrics` might be misleading
I think it should be `exposeHardwareCounterMetrics`

And, "whether expose hardware counter metrics" -> "whether expose hardware counter as prometheus metrics")

2022-10-11 09:34 UTC, marceloamaral commented on pkg/config/config.go
> +	EnabledHardwareCounterMetrics = true
Again, `EnabledHardwareCounterMetrics` might be misleading
We will never disable the hardware counter metrics if they are available, what we might disable is expose those metrics to prometheus...

2022-10-11 09:35 UTC, marceloamaral requested changes
Looks good!
I made some small comments.

2022-10-12 16:50 UTC, rootfs approved these changes

2022-10-12 16:54 UTC, rootfs commented
@marceloamaral ready to merge?

2022-10-13 05:14 UTC, jichenjc commented
@marceloamaral please check whether it's ok to you now :)

2022-10-13 07:45 UTC, marceloamaral approved these changes
Yes, it is good. Thanks!

2022-10-13 07:46 UTC, merged