unit test: test pod and node collector metrics
sustainable-computing-io/kepler pull request #358
Opened 2022-11-03 17:38 UTC by rootfs

add test coverage. Note some functions are not yet fully implemented, the stub tests are to be filled once they are properly implemented.

2022-11-04 08:43 UTC, SamYuan1990 commented
let me know once fixed with CI.

2022-11-07 03:23 UTC, marceloamaral commented
This is a very good test. But the test is failing....

Btw, all of Curr and Agg logic could be improved later...
It would be much better to have a cache array, and then we can get the `Latest` value and the `Sum` value....Also the cache array probably need to be a cycle array due to space limit.

2022-11-08 20:51 UTC, rootfs commented
@SamYuan1990 @marceloamaral issues fixed

2022-11-09 04:33 UTC, SamYuan1990 requested changes

2022-11-09 04:33 UTC, SamYuan1990 commented on pkg/collector/metric/container_metric_test.go
> +		Expect(err).To(BeNil())
```suggestion
		Expect(err).NotTo(HaveOccurred())
```

2022-11-09 04:33 UTC, SamYuan1990 commented on pkg/collector/metric/container_metric_test.go
> +		Expect(err).To(BeNil())
same for others.

2022-11-09 14:48 UTC, rootfs commented
@SamYuan1990 suggestion merged

2022-11-09 15:03 UTC, SamYuan1990 requested changes

2022-11-09 15:03 UTC, SamYuan1990 commented on pkg/collector/metric/container_metric_test.go
> +		Expect(err).To(BeNil())
```suggestion
		Expect(err).NotTo(HaveOccurred())
```

2022-11-11 07:19 UTC, marceloamaral approved these changes
/lgtm

We can refactor things later.

2022-11-11 10:46 UTC, SamYuan1990 approved these changes
LGTM

2022-11-11 10:46 UTC, merged